Matrices

In [5]:
import numpy as np
import sys

In [6]:
np.__version__

'1.26.3'

In [8]:
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [9]:
#Creating Arrays
my_list=[0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [10]:
type(my_list)

list

In [11]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,2) 

array([], dtype=int32)

In [20]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [21]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [22]:
np.arange(30,20)

array([], dtype=int32)

In [23]:
b=np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [24]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [25]:
np.arange(-10,20,5)

array([-10,  -5,   0,   5,  10,  15])

In [26]:
np.arange(-20,50,3)

array([-20, -17, -14, -11,  -8,  -5,  -2,   1,   4,   7,  10,  13,  16,
        19,  22,  25,  28,  31,  34,  37,  40,  43,  46,  49])

In [27]:
ar=np.arange(-20,10)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [28]:
np.arange()

TypeError: arange() requires stop to be specified.

In [29]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [30]:
np.arange(10,100,13)

array([10, 23, 36, 49, 62, 75, 88])

In [31]:
np.arange(0,10,9)

array([0, 9])

In [32]:
np.arange(0,20,3,2) 

TypeError: Cannot interpret '2' as a data type

In [33]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [34]:
np.zeros(3) #parameter tuning

array([0., 0., 0.])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros(4,dtype=int) #hyperparameter tuning

array([0, 0, 0, 0])

In [39]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
zero=np.zeros([3,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [42]:
zero=np.zeros([2,4])
print(zero)
print(type(zero))
id(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


1995448944464

In [43]:
np.arange(2,30)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros([10,30])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [46]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
n=(5,7)
n1=(4,8)
print('parameter tuning \n\n',np.zeros(n),'\n') #parameter tuning
print("hyperparameter tuning \n\n",np.zeros(n1,dtype=int)) ## hyperparameter tuning

parameter tuning 

 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

hyperparameter tuning 

 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [48]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [49]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [50]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [51]:
np.ones(3)

array([1., 1., 1.])

In [52]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [56]:
n

(5, 7)

In [57]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [59]:
n

(5, 7)

In [60]:
np.ones(n1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
np.zeros(n)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [62]:
ar=np.ones([3,5])
ar

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
np.ones((5,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [64]:
np.ones((1,15,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [65]:
np.ones((2,6,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [66]:
print(type(ar))

<class 'numpy.ndarray'>


In [67]:
np.random.rand(5)

array([0.65900578, 0.90036833, 0.57837634, 0.54646409, 0.09946156])

In [68]:
np.random.rand(3)

array([0.95204164, 0.20594831, 0.48325158])

In [69]:
np.random.rand(2,2)

array([[0.36610018, 0.11667807],
       [0.28684878, 0.06487947]])

In [70]:
np.random.rand(2,4)

array([[0.9750669 , 0.76816544, 0.78922556, 0.03071196],
       [0.80817752, 0.78738695, 0.01926895, 0.20443741]])

In [71]:
np.random.randint(0,9)

5

In [72]:
np.random.randint(100)

52

In [73]:
np.random.randint(10,50)

21

In [74]:
np.array([10,20,24,30])

array([10, 20, 24, 30])

In [75]:
np.zeros((2,6,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [76]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [77]:
np.three((3,2))

AttributeError: module 'numpy' has no attribute 'three'

In [78]:
b=np.random.randint(10,20,(5,4))
b

array([[19, 15, 18, 17],
       [19, 19, 11, 19],
       [10, 12, 11, 15],
       [13, 10, 19, 19],
       [18, 18, 18, 13]])

In [79]:
b[:]

array([[19, 15, 18, 17],
       [19, 19, 11, 19],
       [10, 12, 11, 15],
       [13, 10, 19, 19],
       [18, 18, 18, 13]])

In [80]:
b[1:3]

array([[19, 19, 11, 19],
       [10, 12, 11, 15]])

In [81]:
b[1,3]

19

In [82]:
b[2:3]

array([[10, 12, 11, 15]])

In [83]:
b[0:-1]

array([[19, 15, 18, 17],
       [19, 19, 11, 19],
       [10, 12, 11, 15],
       [13, 10, 19, 19]])

# importing numpy in another format (from numpy import *)

In [84]:
from numpy import *   #internally it called all 217 functionality

In [85]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arange(1,5)

array([1, 2, 3, 4])

In [87]:
arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [88]:
arange(10,20,3)

array([10, 13, 16, 19])

In [89]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [90]:
zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [91]:
range(12)

range(0, 12)

In [92]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [93]:
y=list(range(9))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [94]:
surya=list(range(27))
surya

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26]

In [95]:
rand(3,2)

NameError: name 'rand' is not defined

In [96]:
random.rand(3,2)

array([[0.23945061, 0.43366017],
       [0.25672467, 0.53442808],
       [0.141477  , 0.23769701]])

In [97]:
random.rand(4,5)

array([[0.95496753, 0.90686827, 0.89012337, 0.09504053, 0.34193993],
       [0.01852114, 0.44581096, 0.82410294, 0.3554158 , 0.99323071],
       [0.66310394, 0.02218756, 0.58282314, 0.53442141, 0.34787126],
       [0.90294135, 0.9626998 , 0.67477015, 0.07214422, 0.82860653]])

In [98]:
random.rand(3)

array([0.81551044, 0.64220185, 0.71525228])

In [99]:
np.random.rand(3)

array([0.71315325, 0.37199763, 0.10643752])

In [100]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [101]:
random.rand(5)

array([0.00167558, 0.12027827, 0.34344175, 0.40518407, 0.90807942])

In [102]:
np.random.randint(10)

7

In [103]:
np.random.randint(2,10)

8

In [104]:
random.randint(2,50)

29

In [105]:
np.random.randint(1,10,3)

array([1, 4, 5])

In [106]:
random.randint(1,20,5)

array([16,  5, 19,  9, 16])

In [107]:
random.randint(1,10,20)

array([3, 8, 8, 1, 2, 9, 6, 9, 1, 6, 4, 8, 6, 9, 7, 3, 1, 6, 6, 3])

In [108]:
random.randint(10,40,(10,10))

array([[30, 12, 38, 37, 38, 28, 21, 23, 24, 24],
       [26, 28, 29, 26, 35, 19, 26, 29, 26, 36],
       [24, 35, 26, 16, 36, 31, 29, 38, 18, 19],
       [14, 33, 25, 35, 39, 27, 13, 18, 33, 11],
       [13, 11, 21, 32, 13, 32, 10, 39, 36, 32],
       [37, 12, 30, 24, 16, 12, 11, 26, 25, 10],
       [24, 28, 17, 10, 26, 38, 34, 36, 25, 37],
       [28, 31, 10, 39, 17, 28, 10, 19, 11, 22],
       [22, 16, 26, 18, 39, 39, 15, 21, 27, 15],
       [11, 38, 15, 20, 22, 39, 28, 30, 19, 19]])

In [109]:
random.randint(5,9)

7

In [110]:
#generate the elements 10-30 with 4*4 matrix
random.randint(10,30,(4,4))

array([[28, 15, 28, 20],
       [16, 28, 25, 19],
       [17, 12, 15, 11],
       [27, 21, 16, 11]])

In [111]:
b=random.randint(10,20,(5,4))
b

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18],
       [12, 18, 14, 10]])

In [112]:
b[:]

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18],
       [12, 18, 14, 10]])

In [113]:
b[0:2]

array([[17, 12, 13, 17],
       [19, 16, 13, 14]])

In [114]:
b

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18],
       [12, 18, 14, 10]])

In [115]:
b[0:-1]  #0 to (n-1)--(-1-1=-2 so it will print 0th index to -2)

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18]])

In [116]:
b

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18],
       [12, 18, 14, 10]])

In [117]:
b[0,2]

13

In [118]:
b[1:3]

array([[19, 16, 13, 14],
       [11, 10, 13, 18]])

In [119]:
b[0:7]

array([[17, 12, 13, 17],
       [19, 16, 13, 14],
       [11, 10, 13, 18],
       [13, 12, 14, 18],
       [12, 18, 14, 10]])

In [120]:
b[:2]

array([[17, 12, 13, 17],
       [19, 16, 13, 14]])

In [121]:
b[3:]

array([[13, 12, 14, 18],
       [12, 18, 14, 10]])

In [122]:
b[2] #by default it consider row

array([11, 10, 13, 18])

In [123]:
b[4,]

array([12, 18, 14, 10])

In [124]:
b[4,0]

12

In [125]:
random.randint(10,20,(4,4))

array([[18, 19, 14, 19],
       [15, 13, 14, 14],
       [19, 19, 14, 18],
       [15, 14, 17, 11]])

# Operations

In [126]:
 a=random.randint(10,20,5)
a

array([18, 10, 17, 12, 14])

In [127]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
arr2=random.randint(0,100,(10,10))
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [129]:
arr


array([0, 1, 2, 3, 4, 5])

In [130]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [131]:
arr[1:3]

array([1, 2])

In [132]:
arr[:4]

array([0, 1, 2, 3])

In [133]:
arr[2:]

array([2, 3, 4, 5])

In [134]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [135]:
arr2[:]

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [136]:
arr2[0:5]

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31]])

In [137]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [138]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [139]:
arr2[2,-1]

6

In [140]:
arr2[1,5]

0

In [141]:
arr2[3,7]

7

In [142]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [143]:
arr2[-5,2]

14

In [144]:
arr2[-5,7]

16

In [145]:
arr2[-3,-9]

98

In [146]:
arr2[7,-7]

93

In [147]:
arr2[-5,-5]

59

In [148]:
arr2[1:5]

array([[31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31]])

In [149]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [150]:
arr2[::-1]

array([[88, 51,  3, 43, 34, 60,  1, 42, 93,  4],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [48, 90, 27, 66, 20, 81, 52, 93, 64, 82]])

In [151]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [152]:
arr2[::-2] #it will print in step format

array([[88, 51,  3, 43, 34, 60,  1, 42, 93,  4],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64]])

In [153]:
arr2[::-3]

array([[88, 51,  3, 43, 34, 60,  1, 42, 93,  4],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [48, 90, 27, 66, 20, 81, 52, 93, 64, 82]])

In [154]:
arr

array([0, 1, 2, 3, 4, 5])

In [155]:
arr.max()

5

In [156]:
arr.min()


0

In [157]:
arr2

array([[48, 90, 27, 66, 20, 81, 52, 93, 64, 82],
       [31, 80, 21,  7,  0,  0, 37, 97, 80, 64],
       [53, 34,  6, 18, 82, 26, 52,  3, 79,  6],
       [31, 78, 38, 54, 92, 96,  1,  7, 69, 56],
       [99, 57,  3, 45, 19, 61, 94,  7, 87, 31],
       [11, 67, 14, 15, 30, 59, 84, 16, 21, 38],
       [54, 55, 56, 43, 84, 24, 34, 92, 56, 65],
       [70, 98, 37, 93, 75, 49, 35, 74, 17, 41],
       [12, 90, 37, 95, 98, 11, 96,  3, 90, 16],
       [88, 51,  3, 43, 34, 60,  1, 42, 93,  4]])

In [158]:
arr2.max()

99

In [159]:
arr2.min()

0

In [160]:
arr2.sum()

4898

In [161]:
arr2.mean()

48.98

In [162]:
arr2.sort()

In [163]:
arr2

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93],
       [ 0,  0,  7, 21, 31, 37, 64, 80, 80, 97],
       [ 3,  6,  6, 18, 26, 34, 52, 53, 79, 82],
       [ 1,  7, 31, 38, 54, 56, 69, 78, 92, 96],
       [ 3,  7, 19, 31, 45, 57, 61, 87, 94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84],
       [24, 34, 43, 54, 55, 56, 56, 65, 84, 92],
       [17, 35, 37, 41, 49, 70, 74, 75, 93, 98],
       [ 3, 11, 12, 16, 37, 90, 90, 95, 96, 98],
       [ 1,  3,  4, 34, 42, 43, 51, 60, 88, 93]])

In [164]:
arr2.all()

False

In [165]:
arr2.any()

True

In [166]:
arr3=arr2.copy

In [167]:
arr3

<function ndarray.copy>

In [168]:
del arr3

In [169]:
arr3

NameError: name 'arr3' is not defined

In [ ]:
arr2

In [170]:
arr2.mean()

48.98

In [171]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
a=arr2
a

In [172]:
median(a)

14.0

In [173]:
b=arr2
b

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93],
       [ 0,  0,  7, 21, 31, 37, 64, 80, 80, 97],
       [ 3,  6,  6, 18, 26, 34, 52, 53, 79, 82],
       [ 1,  7, 31, 38, 54, 56, 69, 78, 92, 96],
       [ 3,  7, 19, 31, 45, 57, 61, 87, 94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84],
       [24, 34, 43, 54, 55, 56, 56, 65, 84, 92],
       [17, 35, 37, 41, 49, 70, 74, 75, 93, 98],
       [ 3, 11, 12, 16, 37, 90, 90, 95, 96, 98],
       [ 1,  3,  4, 34, 42, 43, 51, 60, 88, 93]])

In [174]:
median(b)

50.0

In [175]:
arr2

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93],
       [ 0,  0,  7, 21, 31, 37, 64, 80, 80, 97],
       [ 3,  6,  6, 18, 26, 34, 52, 53, 79, 82],
       [ 1,  7, 31, 38, 54, 56, 69, 78, 92, 96],
       [ 3,  7, 19, 31, 45, 57, 61, 87, 94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84],
       [24, 34, 43, 54, 55, 56, 56, 65, 84, 92],
       [17, 35, 37, 41, 49, 70, 74, 75, 93, 98],
       [ 3, 11, 12, 16, 37, 90, 90, 95, 96, 98],
       [ 1,  3,  4, 34, 42, 43, 51, 60, 88, 93]])

In [176]:
arr

array([0, 1, 2, 3, 4, 5])

In [177]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [178]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [179]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [180]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [181]:
arr2.reshape(1,100)

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93,  0,  0,  7, 21, 31, 37,
        64, 80, 80, 97,  3,  6,  6, 18, 26, 34, 52, 53, 79, 82,  1,  7,
        31, 38, 54, 56, 69, 78, 92, 96,  3,  7, 19, 31, 45, 57, 61, 87,
        94, 99, 11, 14, 15, 16, 21, 30, 38, 59, 67, 84, 24, 34, 43, 54,
        55, 56, 56, 65, 84, 92, 17, 35, 37, 41, 49, 70, 74, 75, 93, 98,
         3, 11, 12, 16, 37, 90, 90, 95, 96, 98,  1,  3,  4, 34, 42, 43,
        51, 60, 88, 93]])

In [182]:
arr2.reshape(2,50)

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93,  0,  0,  7, 21, 31, 37,
        64, 80, 80, 97,  3,  6,  6, 18, 26, 34, 52, 53, 79, 82,  1,  7,
        31, 38, 54, 56, 69, 78, 92, 96,  3,  7, 19, 31, 45, 57, 61, 87,
        94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84, 24, 34, 43, 54, 55, 56,
        56, 65, 84, 92, 17, 35, 37, 41, 49, 70, 74, 75, 93, 98,  3, 11,
        12, 16, 37, 90, 90, 95, 96, 98,  1,  3,  4, 34, 42, 43, 51, 60,
        88, 93]])

In [183]:
arr2.reshape(4,25)

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93,  0,  0,  7, 21, 31, 37,
        64, 80, 80, 97,  3,  6,  6, 18, 26],
       [34, 52, 53, 79, 82,  1,  7, 31, 38, 54, 56, 69, 78, 92, 96,  3,
         7, 19, 31, 45, 57, 61, 87, 94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84, 24, 34, 43, 54, 55, 56,
        56, 65, 84, 92, 17, 35, 37, 41, 49],
       [70, 74, 75, 93, 98,  3, 11, 12, 16, 37, 90, 90, 95, 96, 98,  1,
         3,  4, 34, 42, 43, 51, 60, 88, 93]])

In [184]:
arr2.reshape(2,50)

array([[20, 27, 48, 52, 64, 66, 81, 82, 90, 93,  0,  0,  7, 21, 31, 37,
        64, 80, 80, 97,  3,  6,  6, 18, 26, 34, 52, 53, 79, 82,  1,  7,
        31, 38, 54, 56, 69, 78, 92, 96,  3,  7, 19, 31, 45, 57, 61, 87,
        94, 99],
       [11, 14, 15, 16, 21, 30, 38, 59, 67, 84, 24, 34, 43, 54, 55, 56,
        56, 65, 84, 92, 17, 35, 37, 41, 49, 70, 74, 75, 93, 98,  3, 11,
        12, 16, 37, 90, 90, 95, 96, 98,  1,  3,  4, 34, 42, 43, 51, 60,
        88, 93]])

In [185]:
arr

array([0, 1, 2, 3, 4, 5])

In [186]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [187]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [188]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [189]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [190]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [191]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [192]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [193]:
arr

array([0, 1, 2, 3, 4, 5])

In [194]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [195]:
mat=np.arange(0,100).reshape(10,10)

In [196]:

mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
row=4
col=5

In [198]:
col

5

In [199]:
row

4

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[row,col]

45

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[3,8]

38

In [206]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [207]:
col=6


In [208]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [210]:
mat[col:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [212]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [214]:
row

4

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [217]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [219]:
mat[:8]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [220]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [221]:
mat[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [222]:
mat[:-3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [223]:
mat[-3]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [224]:
mat[:,-4]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
row

4

In [227]:
col

6

In [228]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [229]:
mat[1,4]

14

In [230]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [231]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [232]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [236]:
mat[:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [237]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [240]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[0:10:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [244]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [245]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [250]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [252]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [253]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [254]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [255]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [257]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [258]:
mat[4,8]

48

In [259]:
mat[0,8]

8

In [260]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[2:6,2:4]    #2:6---> only row part /// 2:4---> it indicates only column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [264]:
mat[3:7,3:8]

array([[33, 34, 35, 36, 37],
       [43, 44, 45, 46, 47],
       [53, 54, 55, 56, 57],
       [63, 64, 65, 66, 67]])

In [266]:
mat[1:4,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [267]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
mat[0,1]

1

In [269]:
mat[1,6]

16

In [270]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [273]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [274]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [275]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [276]:
mat[3,5]

35

In [277]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
mat[1:2,2:4]

array([[12, 13]])

In [279]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [282]:
mat[2:3,2:3]

array([[22]])

In [283]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [284]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [285]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [286]:
mat[2:3,4:5]

array([[24]])

# Masking

In [287]:
mat  # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [288]:
id(mat)

1995450828144

In [289]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [290]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [291]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [292]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [293]:
mat>50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [294]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [295]:
mat[mat==50]

array([50])

In [296]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [297]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [298]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [299]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [300]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [302]:
a3=mat[mat>=50]
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [303]:
a4=mat[mat<=50]
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [305]:
a5=mat[mat==50]
a5

array([50])

In [306]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [307]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [308]:
mat==50


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [309]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [310]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [311]:
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [312]:
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [313]:
a5

array([50])

In [314]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [315]:
mat[mat%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [316]:
mat[mat%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])